version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16
    container_name: notes-blog-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: notes_blog_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - notes-blog-network

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: notes-blog-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    networks:
      - notes-blog-network

  # Next.js Application (Development)
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: notes-blog-app-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/notes_blog_dev
      - REDIS_URL=redis://redis:6379
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-secret-key-here
      - GOOGLE_CLIENT_ID=your-google-client-id
      - GOOGLE_CLIENT_SECRET=your-google-client-secret
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - postgres
      - redis
    networks:
      - notes-blog-network
    command: npm run dev

volumes:
  postgres_data_dev:
  redis_data_dev:

networks:
  notes-blog-network:
    driver: bridge
