version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: notes-blog-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: notes_blog
      POSTGRES_USER: notes_user
      POSTGRES_PASSWORD: notes_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - notes-blog-network

  # Optional: pgAdmin for database management
volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  notes-blog-network:
    driver: bridge
